### ISSUE TITLE
Plugin doesn't show up in Admin > Plugins list

### ISSUE THREAD

**Issue by flow7** [Nykold/nyk-authors#1]
Hi there,
I yesterday installed the plugin using the Admin interface, but for some reason it doesn't show up in the plugins list.
However,
- the user/plugins/authors folder was created, including the blueprints.yaml and the nyk-authors.yaml.
- the nyk-authors.yaml states `enabled: true` in the first line.
- but there is no user/config/plugins/authors.yaml or nyk-authors.yaml.
  
I'm on the most recent Grav version.

Could it be, that the names are confusing? the plugin is called nyk-authors, whereas the main folder is called just 'authors' 
Thanks

**Comment by Nykold** [comment]
Hello!

Your assumption based on the wrong names was exactly correct. The plugin was incorrectly registered in Grav Package Manager and would download into the wrong folder, which would break it.

I filed an issue on the Grav repository asking for a fix and they did it very quickly. On my end, it now seems to be fine.

To fix your installation, please delete the 'authors' folder and re-install. It should now create a 'nyk-authors' folder and work. If, for some reason, it still doesn't work, please refer temporarily to the alternative installation methods.

Thank you for the help.
